baseURL = "https://blog.geyuxu.com/"
languageCode = "cn-zh"
title = "于九博客"
theme = "m10c"
canonifyurls = false


[params]
  author = "yasin.gee"
  description = "凡有选择必有成本"
  avatar = "http://wx3.sinaimg.cn/large/5bc6187cly8g48tf52zvej20u00u0wfo.jpg"
  BeianURL = "http://beian.miit.gov.cn"
  BeianTXT = "苏ICP备14055844号"

[[params.link]]
  name = "HOME"
  url = "/"

[[params.link]]
  name = "TAGS"
  url = "/tags"

[[params.link]]
  name = "技术分享会"
  url = "/tags/技术分享会/"

[[params.social]]
  name = "github"
  url = "https://github.com/geyuxu"

[[params.social]]
  name = "weibo"
  url = "https://weibo.com/geyuxu"



[params.style]
  lightestColor = "#05191E"
  lightColor = "#212121"
  darkColor = "#fff"
  darkestColor = "#C43C3C"
  primaryColor = "#000"
