baseURL = "https://blog.geyuxu.com/"
languageCode = "cn-zh"
title = "于九博客"
theme = "m10c"


[params]
  author = "yasin.gee"
  description = "凡有选择必有成本"
  avatar = "http://wx3.sinaimg.cn/large/5bc6187cly8g48tf52zvej20u00u0wfo.jpg"
  BeianURL = "http://beian.miit.gov.cn"
  BeianTXT = "苏ICP备14055844号"

[[params.social]]
  name = "github"
  url = "https://github.com/geyuxu"

[[params.social]]
  name = "weibo"
  url = "https://www.weibo.com/573005502"

[params.style]
  darkestColor = "#05191E"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
  
